name: Node CI

on: [push]

jobs:
  build:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm ci
      env:
        CI: true
    - name: build
      run: |
        npm run build
      env:
        CI: true
    - name: lint
      run: |
        npm run lint
      env:
        CI: true
    - name: test
      run: |
        npm run test-ci
      env:
        CI: true
