name: Publish Master

on: 
  push:
    branches: 
      - master

jobs:
  build:
    name: Publish master branch as "next" tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: https://registry.npmjs.org/
      - name: install
      - run: npm ci
        env:
          CI: true
      - name: build
        run: npm run build
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: prerelease version
        run: npm run prerelease-version
      - run: npm run publish-prerelease
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
